import type { Metadata } from 'next';
import CaseStudyLayout from '@/components/templates/CaseStudyLayout';
import type { CaseStudyData } from '@/components/templates/CaseStudyLayout';

export const metadata: Metadata = {
  title: 'Revit Plugins | Jonathan Pohlner',
  description:
    'Case study: C# plugins for Autodesk Revit automating drafting workflows.',
};

const project: CaseStudyData = {
  title: 'Revit Plugins',
  tagline:
    'Automating architectural drafting workflows with C# and the Revit API',
  heroImage: {
    src: '/portfolio/revit-plugins/hero.png',
    alt: 'Storefront elevation with automated dimensioning generated by Revit plugin',
  },
  problem:
    'Architects at Trinam Design spent significant time on repetitive drafting tasks in Autodesk Revit — placing elements, generating schedules, and formatting drawings. These manual processes were error-prone and slowed down project delivery.',
  solution:
    "I developed custom C# plugins for Autodesk Revit that automated repetitive drafting workflows, including element placement, schedule generation, and drawing formatting. The plugins integrated with Revit's API and WinForms UI, reducing manual work and improving accuracy across the team's projects.",
  solutionImages: [
    {
      src: '/portfolio/revit-plugins/floor-plan.png',
      alt: 'Floor plan with automated purple dimension markers',
      caption:
        'Automated floor plan dimensioning — plugin adds all measurements in one click',
    },
    {
      src: '/portfolio/revit-plugins/curtain-grid.png',
      alt: '3D curtain wall with automated grid dimensioning',
      caption:
        '3D curtain wall grid dimensioning with automated spacing calculations',
    },
    {
      src: '/portfolio/revit-plugins/shop-elevation.png',
      alt: 'Shop window elevation with automated dimensions',
      caption:
        'Shop elevation with plugin-generated dimension chains and panel labels',
    },
  ],
  techStack: ['C#', '.NET Framework', 'Revit API', 'WinForms', 'Visual Studio'],
};

export default function RevitPluginsPage() {
  return <CaseStudyLayout project={project} />;
}
