import Link from 'next/link';
import { LayeredTurtleWolfeLogo } from '@/components/atomic/SpinningLogo';
import { AnimatedLogo } from '@/components/atomic/AnimatedLogo';
import TemplateStats, {
  type TemplateStat,
  type TemplateDemo,
} from '@/components/molecular/TemplateStats';
import ProjectShowcaseCard from '@/components/molecular/ProjectShowcaseCard';
import CTABanner from '@/components/molecular/CTABanner';

// ── Portfolio landing — audience is potential employers and collaborators.
//     Visual hierarchy: spinning logo + animated name draw the eye,
//     project showcase, stats, certifications, community, and CTA. ──

const STATS: readonly TemplateStat[] = [
  {
    value: '10+',
    label: 'Years Experience',
    detail: 'Web development & design',
    href: '/about',
  },
  {
    value: '20+',
    label: 'Web Apps Built',
    detail: 'Small business & enterprise',
    href: '/services',
  },
  {
    value: 'WCAG AA',
    label: 'Accessible',
    detail: 'Skip links · font scaling',
    href: '/accessibility',
  },
  {
    value: 'PWA',
    label: 'Offline-First',
    detail: 'Service worker · installable',
    href: '/blog',
  },
];

const DEMOS: readonly TemplateDemo[] = [
  { label: 'Blog', href: '/blog' },
  { label: 'Wireframes', href: '/wireframes' },
  { label: 'Contact', href: '/contact' },
  { label: 'Themes', href: '/themes' },
  { label: 'Status', href: '/status' },
  {
    label: 'Storybook',
    href: 'https://tortoisewolfe.github.io/TurtleWolfe/storybook/',
    external: true,
  },
];

const FEATURED_PROJECTS = [
  {
    title: 'SpokeToWork',
    description:
      'Job-hunting-by-bicycle PWA with MapLibre GL route planning, company management, and end-to-end encrypted messaging.',
    image: {
      src: '/portfolio/spoketo-work/map-view.png',
      alt: 'SpokeToWork app showing map view with cycling routes to employers',
    },
    stack: ['Next.js', 'MapLibre', 'Supabase', 'ECDH'],
    href: '/projects/spoketo-work',
    hasDetailPage: true,
  },
  {
    title: 'ScriptHammer',
    description:
      'Production-ready Next.js template with 32 DaisyUI themes, Docker-first workflow, Storybook, full CI/CD, and tech blog.',
    image: {
      src: '/portfolio/scripthammer/hero.png',
      alt: 'ScriptHammer template showing theme switcher and component library',
    },
    stack: ['Next.js 15', 'DaisyUI', 'Docker', 'Storybook'],
    href: '/projects/scripthammer',
    hasDetailPage: true,
  },
  {
    title: 'Revit Plugins',
    description:
      'C# plugins for Autodesk Revit automating drafting workflows at Trinam Design — reducing repetitive tasks for architects.',
    image: {
      src: '/portfolio/revit-plugins/hero.png',
      alt: 'Storefront elevation with automated dimensioning generated by Revit plugin',
    },
    stack: ['C#', 'Revit API', 'WinForms', '.NET'],
    href: '/projects/revit-plugins',
    hasDetailPage: true,
  },
] as const;

const OTHER_PROJECTS = [
  {
    title: 'Interactive Resume',
    description:
      'Live portfolio resume showcasing projects and skills — mobile-first responsive design on GitHub Pages.',
    image: {
      src: '/portfolio/other/interactive-resume.png',
      alt: 'Interactive resume showing project showcase and skills',
    },
    stack: ['React', 'GitHub Pages', 'Responsive'],
    href: 'https://tortoisewolfe.github.io/Resume/',
  },
  {
    title: 'The House that Code Built',
    description:
      'Published children\u2019s picture book introducing programming concepts — HTML is the framework, CSS is the wallpaper, JavaScript is the electrical.',
    image: {
      src: '/portfolio/other/house-that-code-built.png',
      alt: "The House that Code Built children's book website",
    },
    stack: ['Education', 'Publishing', 'Community'],
    href: 'https://tortoisewolfe.github.io/The_House_that_Code_Built/',
  },
  {
    title: 'MoltBot / Automated Twitch',
    description:
      'AI-powered 24/7 Twitch channel using Remotion for programmatic video generation and MoltBot agent pipeline.',
    image: {
      src: '/portfolio/other/scripthammer-twitch.png',
      alt: 'ScriptHammer automated Twitch channel showing AI-generated content',
    },
    stack: ['Remotion', 'AI Agents', 'Twitch API'],
    href: 'https://twitch.tv/ScriptHammer',
  },
  {
    title: 'Mercor AI Evaluation',
    description:
      'A/B testing framework for evaluating AI coding assistants — Python validation tools, multi-track test orchestration, behavioral analysis.',
    stack: ['Python', 'Docker', 'Bash', 'tmux'],
    href: 'https://github.com/TortoiseWolfe',
  },
  {
    title: 'DevCamper API',
    description:
      'RESTful bootcamp directory API with JWT auth and role-based access control.',
    image: {
      src: '/portfolio/other/devcamper-api.png',
      alt: 'DevCamper API GitHub repository',
    },
    stack: ['Node.js', 'Express', 'MongoDB'],
    href: 'https://github.com/TurtleWolfe/DevCamperAPIv001',
  },
  {
    title: 'FreeCodeCamp',
    description:
      'Frontend Libraries certification projects — React, D3 visualizations, responsive design.',
    image: {
      src: '/portfolio/other/freecodecamp.png',
      alt: 'FreeCodeCamp projects GitHub repository',
    },
    stack: ['React', 'D3.js', 'Bootstrap'],
    href: 'https://github.com/TurtleWolfe/fccTempLate',
  },
  {
    title: 'GrimGlow',
    description:
      'Multimedia IP design bible — comic, Three.js, and Unity prototypes.',
    image: {
      src: '/portfolio/other/grimglow.png',
      alt: 'GrimGlow planning repository',
    },
    stack: ['Three.js', 'Unity', 'Design'],
    href: 'https://github.com/TortoiseWolfe/GrimGlow_planning',
  },
] as const;

const SOCIAL_LINKS = [
  {
    label: 'GitHub',
    href: 'https://github.com/TortoiseWolfe',
    icon: (
      <svg viewBox="0 0 24 24" fill="currentColor" className="h-5 w-5">
        <path d="M12 0C5.374 0 0 5.373 0 12c0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23A11.509 11.509 0 0112 5.803c1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576C20.566 21.797 24 17.3 24 12c0-6.627-5.373-12-12-12z" />
      </svg>
    ),
  },
  {
    label: 'LinkedIn',
    href: 'https://linkedin.com/in/pohlner',
    icon: (
      <svg viewBox="0 0 24 24" fill="currentColor" className="h-5 w-5">
        <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z" />
      </svg>
    ),
  },
  {
    label: 'Twitch',
    href: 'https://twitch.tv/turtlewolfe',
    icon: (
      <svg viewBox="0 0 24 24" fill="currentColor" className="h-5 w-5">
        <path d="M11.571 4.714h1.715v5.143H11.57zm4.715 0H18v5.143h-1.714zM6 0L1.714 4.286v15.428h5.143V24l4.286-4.286h3.428L22.286 12V0zm14.571 11.143l-3.428 3.428h-3.429l-3 3v-3H6.857V1.714h13.714Z" />
      </svg>
    ),
  },
  {
    label: 'YouTube',
    href: 'https://www.youtube.com/@JonathanPohlner',
    icon: (
      <svg viewBox="0 0 24 24" fill="currentColor" className="h-5 w-5">
        <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z" />
      </svg>
    ),
  },
  {
    label: 'Twitter',
    href: 'https://twitter.com/JonPohlner',
    icon: (
      <svg viewBox="0 0 24 24" fill="currentColor" className="h-5 w-5">
        <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
      </svg>
    ),
  },
  {
    label: 'ScriptHammer',
    href: 'https://twitch.tv/ScriptHammer',
    icon: (
      <svg viewBox="0 0 24 24" fill="currentColor" className="h-5 w-5">
        <path d="M11.571 4.714h1.715v5.143H11.57zm4.715 0H18v5.143h-1.714zM6 0L1.714 4.286v15.428h5.143V24l4.286-4.286h3.428L22.286 12V0zm14.571 11.143l-3.428 3.428h-3.429l-3 3v-3H6.857V1.714h13.714Z" />
      </svg>
    ),
  },
] as const;

const CERTIFICATIONS = [
  {
    title: 'FreeCodeCamp',
    description:
      'Front End Libraries Certification — React, Redux, Bootstrap, jQuery, Sass',
    date: '2018 – 2021',
    href: 'https://www.freecodecamp.org/certification/turtlewolf/front-end-development-libraries',
  },
  {
    title: 'Udemy API Masterclass',
    description:
      'Node.js API with Express & MongoDB — REST, JWT auth, file uploads, geocoding',
    date: '2020',
    href: 'https://www.udemy.com/certificate/UC-8033cc47-612f-4a7b-afc3-c7a8c9273686/',
  },
  {
    title: 'Indeed Assessments',
    description:
      'Software Developer Skills (Proficient), Problem Solving (Expert), Basic Computer Skills (Expert)',
    date: 'Verified (Discontinued)',
    href: '',
  },
] as const;

export default function Home() {
  return (
    <main className="bg-base-200 flex min-h-full flex-col">
      {/* Skip link — load-bearing a11y, do not remove (PRP-017 T036). */}
      <a
        href="#main-content"
        className="btn btn-sm btn-primary sr-only min-h-11 min-w-11 focus:not-sr-only focus:absolute focus:top-4 focus:left-4"
      >
        Skip to main content
      </a>

      {/* ── Hero ─────────────────────────────────────────────────────── */}
      <section
        id="main-content"
        aria-labelledby="hero-heading"
        className="mx-auto w-full max-w-6xl flex-1 px-4 py-16 sm:px-6 lg:px-8 lg:py-24"
      >
        <div className="flex flex-col items-center gap-8 lg:flex-row lg:gap-16">
          {/* Logo */}
          <div className="flex-shrink-0">
            <div className="h-48 w-48 sm:h-52 sm:w-52 md:h-56 md:w-56 lg:h-[350px] lg:w-[350px]">
              <LayeredTurtleWolfeLogo speed="slow" pauseOnHover />
            </div>
          </div>

          {/* Content */}
          <div className="text-center lg:text-left">
            <h1 id="hero-heading" className="mb-2 sm:mb-4">
              <AnimatedLogo
                text="Jonathan Pohlner"
                className="!text-2xl font-bold sm:!text-3xl md:!text-5xl lg:!text-6xl"
                animationSpeed="normal"
              />
            </h1>

            <p className="text-primary mb-2 text-lg font-semibold sm:text-xl">
              Full Stack Developer
            </p>

            <p className="text-base-content/60 mb-4 text-base italic sm:text-lg">
              Putting the &lsquo;Service&rsquo; in &ldquo;Software as a
              Service&rdquo;
            </p>

            <p className="text-base-content/80 mb-6 max-w-2xl text-lg leading-relaxed sm:text-xl">
              10+ years building accessible web applications with React,
              TypeScript, and Next.js. 20+ years in graphic design.
            </p>

            {/* Tech stack badges */}
            <div
              className="mb-6 flex flex-wrap justify-center gap-2 lg:justify-start"
              role="list"
              aria-label="Technology stack"
            >
              {[
                'React',
                'React Native',
                'TypeScript',
                'Next.js',
                'Node.js',
                'Three.js',
                'C#',
                'Python',
                'Docker',
                'AWS',
                'Linux',
                'MongoDB',
                'Supabase',
                'Tailwind',
              ].map((tech) => (
                <span
                  key={tech}
                  role="listitem"
                  className="badge badge-outline badge-sm sm:badge-md"
                >
                  {tech}
                </span>
              ))}
            </div>

            {/* Social links */}
            <div className="mb-8 flex justify-center gap-3 lg:justify-start">
              {SOCIAL_LINKS.map((link) => (
                <a
                  key={link.label}
                  href={link.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn btn-ghost btn-circle min-h-11 min-w-11"
                  aria-label={link.label}
                >
                  {link.icon}
                </a>
              ))}
            </div>

            <nav
              aria-label="Primary actions"
              className="flex flex-col items-center gap-4 sm:flex-row sm:justify-center lg:justify-start"
            >
              <Link
                href="/contact"
                className="btn btn-primary btn-lg min-h-11 min-w-11"
              >
                Get in Touch
              </Link>
              <a
                href="https://tortoisewolfe.github.io/Resume/"
                target="_blank"
                rel="noopener noreferrer"
                className="btn btn-outline btn-lg min-h-11 min-w-11"
              >
                View My Resume
              </a>
            </nav>
          </div>
        </div>
      </section>

      {/* ── Featured Projects (with case studies) ──────────────────── */}
      <section
        id="projects"
        aria-label="Featured projects"
        className="section-glow px-4 py-12 sm:px-6 lg:px-8"
      >
        <div className="mx-auto max-w-6xl">
          <h2 className="text-base-content mb-4 text-center text-2xl font-bold sm:text-3xl">
            Featured Projects
          </h2>
          <p className="text-base-content/60 mb-8 text-center text-lg">
            Click any project to see the full case study
          </p>
          <div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
            {FEATURED_PROJECTS.map((p) => (
              <ProjectShowcaseCard
                key={p.title}
                title={p.title}
                description={p.description}
                image={'image' in p ? p.image : undefined}
                stack={[...p.stack]}
                href={p.href}
                hasDetailPage={p.hasDetailPage}
              />
            ))}
          </div>
        </div>
      </section>

      {/* ── More Projects ──────────────────────────────────────────── */}
      <section
        aria-label="More projects"
        className="px-4 py-12 sm:px-6 lg:px-8"
      >
        <div className="mx-auto max-w-6xl">
          <h2 className="text-base-content mb-8 text-center text-2xl font-bold sm:text-3xl">
            More Work
          </h2>
          <div className="grid grid-cols-1 gap-4 min-[500px]:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {OTHER_PROJECTS.map((p) => (
              <ProjectShowcaseCard
                key={p.title}
                title={p.title}
                description={p.description}
                image={'image' in p ? p.image : undefined}
                stack={[...p.stack]}
                href={p.href}
              />
            ))}
          </div>
        </div>
      </section>

      {/* ── Stats + Demos ────────────────────────────────────────────── */}
      <TemplateStats stats={STATS} demos={DEMOS} />

      {/* ── Services Preview ─────────────────────────────────────────── */}
      <section
        aria-label="Services overview"
        className="section-glow px-4 py-12 sm:px-6 lg:px-8"
      >
        <div className="mx-auto max-w-6xl">
          <h2 className="text-base-content mb-4 text-center text-2xl font-bold sm:text-3xl">
            What I Build
          </h2>
          <p className="text-base-content/60 mb-8 text-center text-lg">
            Full-stack solutions from concept to deployment
          </p>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {[
              {
                title: 'Web Applications',
                desc: 'React, Next.js, TypeScript full-stack apps with modern architecture',
                icon: '🖥️',
              },
              {
                title: 'PWA & Offline-First',
                desc: 'Service workers, installable apps, push notifications',
                icon: '📱',
              },
              {
                title: 'Technical Consulting',
                desc: 'Architecture reviews, code audits, team mentoring',
                icon: '🔍',
              },
              {
                title: 'System Modernization',
                desc: 'Migration from legacy stacks to modern React/TypeScript',
                icon: '🔄',
              },
            ].map((s) => (
              <div key={s.title} className="card bg-base-200 shadow-md">
                <div className="card-body items-center text-center">
                  <span className="text-3xl" aria-hidden="true">
                    {s.icon}
                  </span>
                  <h3 className="card-title text-base">{s.title}</h3>
                  <p className="text-base-content/70 text-sm">{s.desc}</p>
                </div>
              </div>
            ))}
          </div>
          <div className="mt-8 text-center">
            <Link
              href="/services"
              className="btn btn-outline min-h-11 min-w-11"
            >
              View All Services
            </Link>
          </div>
        </div>
      </section>

      {/* ── Certifications ──────────────────────────────────────────── */}
      <section
        aria-label="Certifications"
        className="px-4 py-12 sm:px-6 lg:px-8"
      >
        <div className="mx-auto max-w-6xl">
          <h2 className="text-base-content mb-8 text-center text-2xl font-bold sm:text-3xl">
            Certifications
          </h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {CERTIFICATIONS.map((cert) => {
              const cardContent = (
                <div className="card-body p-4">
                  <h3 className="card-title text-primary text-base">
                    {cert.title}
                  </h3>
                  <p className="text-base-content/85 text-xs">
                    {cert.description}
                  </p>
                  <div className="mt-2 flex items-center justify-between">
                    <span className="badge badge-ghost badge-xs">
                      {cert.date}
                    </span>
                    {cert.href && (
                      <span className="text-primary text-xs">
                        View Certificate &rarr;
                      </span>
                    )}
                  </div>
                </div>
              );

              return cert.href ? (
                <a
                  key={cert.title}
                  href={cert.href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="card bg-base-100 shadow-md transition-all hover:-translate-y-1 hover:shadow-lg"
                >
                  {cardContent}
                </a>
              ) : (
                <div key={cert.title} className="card bg-base-100 shadow-md">
                  {cardContent}
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── Community & Teaching ─────────────────────────────────────── */}
      <section
        aria-label="Community involvement"
        className="section-glow px-4 py-12 sm:px-6 lg:px-8"
      >
        <div className="mx-auto max-w-6xl">
          <h2 className="text-base-content mb-8 text-center text-2xl font-bold sm:text-3xl">
            Community & Teaching
          </h2>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-3">
            <div className="card bg-base-200 shadow-md">
              <div className="card-body items-center text-center">
                <h3 className="card-title text-base">Dangerous Minds</h3>
                <p className="text-base-content/70 text-sm">
                  Community group teaching children basic programming concepts
                  through hands-on projects
                </p>
              </div>
            </div>
            <div className="card bg-base-200 shadow-md">
              <div className="card-body items-center text-center">
                <h3 className="card-title text-base">
                  FreeCodeCamp Chattanooga
                </h3>
                <p className="text-base-content/70 text-sm">
                  Chapter administrator — organizing meetups and mentoring new
                  developers
                </p>
              </div>
            </div>
            <a
              href="https://tortoisewolfe.github.io/The_House_that_Code_Built/"
              target="_blank"
              rel="noopener noreferrer"
              className="card bg-base-200 shadow-md transition-all hover:-translate-y-1 hover:shadow-lg"
            >
              <div className="card-body items-center text-center">
                <h3 className="card-title text-primary text-base">
                  The House that Code Built
                </h3>
                <p className="text-base-content/70 text-sm">
                  Published children&apos;s book introducing programming — HTML
                  is the framework, CSS the wallpaper, JavaScript the electrical
                </p>
                <span className="text-primary mt-2 text-xs">
                  Read it online &rarr;
                </span>
              </div>
            </a>
          </div>
        </div>
      </section>

      {/* ── CTA Banner ──────────────────────────────────────────────── */}
      <CTABanner
        headline="Let's build something together"
        description="Whether you need a web application, technical consulting, or a team to modernize your stack — I'm ready to help."
        primaryCTA={{ label: 'Get in Touch', href: '/contact' }}
        secondaryCTA={{
          label: 'View My Resume',
          href: 'https://tortoisewolfe.github.io/Resume/',
          external: true,
        }}
      />
    </main>
  );
}
